apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: local
    data: wordpress
spec:
  storageClassName: standard
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress/wordpress"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  labels:
    type: local
    data: mariadb
spec:
  storageClassName: standard
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress/mariadb"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    type: local
    data: mariadb-backup
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wordpress/mariadb-backup"