---
- name: Tareas comunes a todas las maquinas
  hosts: all
  become: true
  tasks:
    - name: Update system
      shell: 'apt update -y'
      args:
        chdir: /home/ansible
    - name: Set Time to Europe/Madrid-1
      shell: 'timedatectl set-timezone Europe/Madrid'
      args:
        chdir: /home/ansible
    - name: Set Time to Europe/Madrid-2
      shell: 'timedatectl set-ntp true'
      args:
        chdir: /home/ansible
    - name: Install required packages-1
      apt:
        state: present
        update_cache: yes
        name:
          - net-tools
    - name: Install required packages-2
      apt:
        state: present
        update_cache: yes
        name:
          - nfs-common
          - nfs4-acl-tools
    - name: Install required packages-3
      apt:
        state: present
        update_cache: yes
        name:
          - wget
          - chrony
    - name: Install required packages-4
      apt:
        state: present
        update_cache: yes
        name:
          - firewalld
    - name: Activar chrony
      service:
        name: chrony
        state: started
    - name: Cargar /etc/hosts en MV
      copy:
        src: ../files/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

#Ejecutar como primer playbook con
#$ ansible-playbook commontasks.yml -i hosts/inventory.ini
