- hosts: master
  become: yes
  tasks:
    - name: kubernetes config 1
      shell: "mkdir .kube"
      args:
        chdir: /home/ansible
    - name: kubernetes config 2
      shell: "cp -i /etc/kubernetes/admin.conf /home/ansible/.kube/config"
      args:
        chdir: /home/ansible
    - name: kubernetes config 3
      shell: "chown ansible:ansible /home/ansible/.kube/config"
      args:
        chdir: /home/ansible
    - name: install tigera
      shell: "kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml"
      args:
        chdir: /home/ansible