---
- hosts: master
  become: true
  tasks:
    - name: install nfs-kernel
      apt:
        state: present
        update_cache: yes
        name:
          - nfs-kernel-server
    - name: Activar nfs-server
      service:
        name: nfs-server
        state: started
        
    - name: permissions in shared folder
      shell: 'chmod 777 /srv/nfs'
      args:
        chdir: /home/ansible

    - name: Upload /etc/exports to nfs
      copy:
        src: ../files/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
    - name: exportfs 1
      shell: 'exportfs -r'
      args:
        chdir: /home/ansible
    - name: exportfs 2
      shell: 'exportfs -s'
      args:
        chdir: /home/ansible

    - name: Activar firewalld
      service:
        name: firewalld
        state: started
    - name: firewall-cmd 01
      shell: 'firewall-cmd --permanent --add-service=nfs'
      args:
        chdir: /home/ansible
    - name: firewall-cmd 02
      shell: 'firewall-cmd --permanent --add-service=rpc-bind'
      args:
        chdir: /home/ansible
    - name: firewall-cmd 03
      shell: 'firewall-cmd --permanent --add-service=mountd'
      args:
        chdir: /home/ansible
    - name: firewall-cmd 04
      shell: 'firewall-cmd --reload'
      args:
        chdir: /home/ansible

- hosts: all
  become: yes
  tasks:
    - name: mount shared directory
      shell: 'mount 10.0.1.15:/srv/nfs /srv/nfs'
      args:
        chdir: /home/ansible