---
- hosts: nodes
  become: true
  tasks:
    - name: transparent masquerading 1
      shell: 'modprobe br_netfilter'
      args:
        chdir: /home/ansible

    - name: transparent masquerading 2
      shell: 'firewall-cmd --add-masquerade --permanent'
      args:
        chdir: /home/ansible

    - name: transparent masquerading 3
      shell: 'firewall-cmd --reload'
      args:
        chdir: /home/ansible
        
    - name: traficc through firewall 1
      shell:
        cmd: |
          cat <<EOF > /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
      args:
        executable: /bin/bash

    - name: traficc through firewall 2
      shell: 'sysctl --system'
      args:
        chdir: /home/ansible

    - name: install dependences
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: key GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        
    - name: activate docker
      service:
        name: docker
        state: started
        enabled: yes
