---
- hosts: nodes
  become: true
  tasks:
    - name: transparent masquerading 1
      shell: 'modprobe br_netfilter'
      args:
        chdir: /home/ansible

    - name: transparent masquerading 2
      shell: 'firewall-cmd --add-masquerade --permanent'
      args:
        chdir: /home/ansible

    - name: transparent masquerading 3
      shell: 'firewall-cmd --reload'
      args:
        chdir: /home/ansible
        
    - name: traficc through firewall 1
      shell:
        cmd: |
          cat <<EOF > /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
      args:
        executable: /bin/bash

    - name: traficc through firewall 2
      shell: 'sysctl --system'
      args:
        chdir: /home/ansible
    
    - name: install docker 1
      apt:
        state: present
        update_cache: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: install docker 2
      shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -'
      args:
        warn: false # set warn=false to prevent warning
        chdir: /home/ansible

    - name: install docker 3
      shell: 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"'
      args:
        chdir: /home/ansible

    - name: install docker 4
      shell: 'apt update'
      args:
        chdir: /home/ansible

    - name: install docker 5
      get_url:
        url: https://download.docker.com/linux/ubuntu/dists/bionic/pool/edge/amd64/containerd.io_1.2.2-3_amd64.deb
        dest: /home/ansible/containerd.io_1.2.2-3_amd64.deb
        mode: '0744'

    - name: install docker 6
      shell: 'apt install ./containerd.io_1.2.2-3_amd64.deb'
      args:
        chdir: /home/ansible

    - name: install docker 7
      shell: 'apt install docker-ce'
      args:
        chdir: /home/ansible

    - name: install docker 8
      shell: 'usermod -aG docker ansible'
      args:
        chdir: /home/ansible
