---
- hosts: nodes
  become: true
  tasks:
    - name: transparent masquerading 1
      shell: 'modprobe br_netfilter'
      args:
        chdir: /home/ansible
    - name: transparent masquerading 2
      shell: 'firewall-cmd --add-masquerade --permanent'
      args:
        chdir: /home/ansible
    - name: transparent masquerading 3
      shell: 'firewall-cmd --reload'
      args:
        chdir: /home/ansible
    - name: traficc through firewall 1
      shell:
        cmd: |
          cat <<EOF > /etc/sysctl.d/k8s.conf
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          EOF
      args:
        executable: /bin/bash
    - name: traficc through firewall 2
      shell: 'sysctl --system'
      args:
        chdir: /home/ansible


        