---
- name: Tareas comunes a todas las maquinas
  hosts: all
  become: true
  tasks:
    - name: Update system
      shell: 'apt update -y'
      args:
        chdir: /home/ansible
    - name: Set Time to Europe/Madrid-1
      shell: 'timedatectl set-timezone Europe/Madrid'
      args:
        chdir: /home/ansible
    - name: Set Time to Europe/Madrid-2
      shell: 'timedatectl set-ntp true'
      args:
        chdir: /home/ansible
    - name: Install required packages
      apt:
        state: present
        update_cache: yes
        name:
          - nfs-common
          - nfs4-acl-tools wget

